kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deployment-creator
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update