kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: job-creator
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update